### PR TITLE
Mbox fixes

### PR DESCRIPTION
**Pull request by pali**
This pull request fix parsing emails (last line of mboxo/mboxrd variant is ignored), fix documentation format, delete useless check for regular file (Mbox module already supports non-seekable files) and add function messageid() which returns Message-Id.

### CODE REVIEW

**Comment by pali** [comment]
After while... Can somebody review & merge this pull request?

**Comment by rjbs** [comment]
(I emailed SIMONW, who has primary ownership of the dist, as promised.  Will let you know about any reply ASAP.)

**Comment by rjbs** [comment]
I'd like to get permissions for you to upload this to PAUSE, @pali, but I don't see any PAUSE user for you.  Do you have an account?  You'd need one.

**Comment by pali** [comment]
Yes, I have account **pali**.

**Comment by rjbs** [comment]
Thanks, I had missed it in search results because you've got no gravatar, so there was no big image calling my eye out.  Oops!  Anyway, looks like this should get fixed today.

**Pull request merged**
